// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1DH0xZV7SoE6QUFw5Hf5hj14kw8RxqpU',
    appId: '1:991633547360:android:8e45539ea5d32a92d26305',
    messagingSenderId: '991633547360',
    projectId: 'math-battle-arena-6fd75',
    databaseURL: 'https://math-battle-arena-6fd75-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'math-battle-arena-6fd75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBTREUl_46xpBoAu1bCp6e2B67piewql0',
    appId: '1:991633547360:ios:cc4ffef0c66f79b8d26305',
    messagingSenderId: '991633547360',
    projectId: 'math-battle-arena-6fd75',
    databaseURL: 'https://math-battle-arena-6fd75-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'math-battle-arena-6fd75.firebasestorage.app',
    iosBundleId: 'com.example.mathBattleArena',
  );
}
